import { type Program } from "@/types/program";
export const programs: Program[] = [
  {
    id: "bth",
    tab: "B.Th.",
    title: "Bachelor of Theology",
    description:
      "An undergraduate foundation in biblical, theological and ministerial studies — the first step into vocational ministry. Builds language proficiency, ecclesiology and Christian living.",
    level: "Undergraduate",
    duration: "3 Years",
    semesters: "6 Semesters",
    tuition: "₹7,000 / year",
    qualification: "10th + Inter or equivalent",
    cta: "Apply to B.Th.",
    terms: [
      {
        label: "Semester 1",
        courses: [
          "Old Testament Survey",
          "New Testament Survey",
          "Theology Proper",
          "Spiritual Life & Christian Ethics",
          "Evangelism",
          "Elementary Greek 1",
        ],
      },
      {
        label: "Semester 2",
        courses: [
          "Pentateuch",
          "Gospels",
          "Bibliology",
          "Hinduism",
          "Homiletics",
          "Elementary Greek 2",
        ],
      },
      {
        label: "Semester 3",
        courses: [
          "Historical Books",
          "Acts",
          "Christology",
          "Children Ministry",
          "Early Church History",
          "Elementary Greek 3",
        ],
      },
      {
        label: "Semester 4",
        courses: [
          "Poetical Books",
          "Pauline Epistles",
          "Pneumatology",
          "Youth Ministry",
          "Medieval Church History",
          "Elementary Hebrew 1",
        ],
      },
      {
        label: "Semester 5",
        courses: [
          "Major Prophets",
          "Non-Pauline Epistles",
          "Angelology",
          "Leadership",
          "Reformed Church History",
          "Elementary Hebrew 2",
        ],
      },
      {
        label: "Semester 6",
        courses: [
          "Minor Prophets",
          "Revelation",
          "Eschatology",
          "Discipleship",
          "Indian Church History",
          "Elementary Hebrew 3",
        ],
      },
    ],
  },
  {
    id: "mdiv",
    tab: "M.Div.",
    title: "Master of Divinity",
    description:
      "A graduate-level pastoral and theological formation programme equipping students for ordained ministry, church planting and full-time vocational service.",
    level: "Graduate · Ministry track",
    duration: "2 Years",
    semesters: "4 Semesters",
    tuition: "₹10,000 / year",
    qualification: "B.Th. or 10th + Inter or equivalent + Degree",
    cta: "Apply to M.Div.",
    terms: [
      {
        label: "Semester 1",
        courses: [
          "Pentateuch",
          "Gospels",
          "Theology Proper",
          "Bibliology",
          "Spiritual Life & Christian Ethics",
          "Evangelism",
          "Hinduism",
          "Elementary Greek 1",
        ],
      },
      {
        label: "Semester 2",
        courses: [
          "Historical Books",
          "Acts",
          "Christology",
          "Pneumatology",
          "Children & Youth Ministry",
          "Homiletics",
          "Islam",
          "Elementary Greek 2",
        ],
      },
      {
        label: "Semester 3",
        courses: [
          "Poetical Books",
          "Pauline & Non-Pauline Epistles",
          "Soteriology",
          "Ecclesiology",
          "Leadership",
          "Discipleship",
          "Early & Medieval Church History",
          "Elementary Hebrew 1",
        ],
      },
      {
        label: "Semester 4",
        courses: [
          "Major & Minor Prophets",
          "Revelation",
          "Eschatology",
          "Angelology",
          "Pastoral Ministry",
          "Church Planting & Church Growth",
          "Reformed & Indian Church History",
          "Elementary Hebrew 2",
        ],
      },
    ],
  },
  {
    id: "mth",
    tab: "M.Th.",
    title: "Master of Theology",
    description:
      "An advanced post-graduate degree refining exegetical, theological and pastoral skill. Designed for scholar-pastors and future seminary faculty.",
    level: "Post-graduate · Research-oriented",
    duration: "2 Years",
    semesters: "4 Semesters",
    tuition: "₹11,500 / year",
    qualification: "M.Div. or 10th + Inter or equivalent + Degree + B.Th.",
    cta: "Apply to M.Th.",
    terms: [
      {
        label: "Semester 1",
        courses: [
          "Pentateuch",
          "Gospels",
          "Theology Proper",
          "Bibliology",
          "Spiritual Life & Christian Ethics",
          "Evangelism",
          "Hinduism & Islam",
          "Elementary Greek 1",
        ],
      },
      {
        label: "Semester 2",
        courses: [
          "Historical Books",
          "Acts",
          "Christology",
          "Pneumatology",
          "Children & Youth Ministry",
          "Homiletics",
          "Leadership & Discipleship",
          "Elementary Greek 2",
        ],
      },
      {
        label: "Semester 3",
        courses: [
          "Poetical Books",
          "Pauline & Non-Pauline Epistles",
          "Soteriology",
          "Ecclesiology",
          "Pastoral Ministry",
          "Hermeneutics",
          "Early & Medieval Church History",
          "Elementary Hebrew 1",
        ],
      },
      {
        label: "Semester 4",
        courses: [
          "Major & Minor Prophets",
          "Revelation",
          "Eschatology",
          "Angelology",
          "Church Planting & Church Growth",
          "Reformed & Indian Church History",
          "Elementary Hebrew 2",
          "Thesis",
        ],
      },
    ],
  },
  {
    id: "phd",
    tab: "Ph.D.",
    title: "Doctor of Philosophy",
    description:
      "An original-research doctorate. Designed for academic theologians, seminary professors and senior ministry leaders pursuing the highest level of scholarly contribution to the Indian church.",
    level: "Doctoral · Research & Thesis",
    duration: "2 Years",
    semesters: "4 Semesters",
    tuition: "₹12,500 / year",
    qualification: "M.Th. or Post Graduation with any theological qualification",
    cta: "Apply to Ph.D.",
    terms: [
      {
        label: "Semester 1",
        courses: [
          "Old Testament Exegesis",
          "Theology Proper",
          "Bibliology",
          "Christology",
          "Pneumatology",
          "Religions: Hinduism, Islam, Jainism, Sikhism",
        ],
      },
      {
        label: "Semester 2",
        courses: [
          "New Testament Exegesis",
          "Eschatology",
          "Angelology",
          "Soteriology",
          "Ecclesiology",
          "Church History: Early, Medieval, Reformed, Modern (Indian)",
          "Hebrew",
        ],
      },
      {
        label: "Semester 3",
        courses: [
          "Research Methodology",
          "Indian Christian Theology",
          "Missiology",
          "Contemporary Issues: Dalit, Women & Children",
          "Initial Research Proposal",
        ],
      },
      {
        label: "Thesis",
        note: "Full semester dedicated to original doctoral research and thesis completion under faculty supervision.",
      },
    ],
  },
];
