/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutAdvisorRouteImport } from './routes/about/advisor'
import { Route as AboutFacultyRouteImport } from './routes/about/faculty'
import { Route as AboutFounderRouteImport } from './routes/about/founder'
import { Route as AboutStaffRouteImport } from './routes/about/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAdvisorRoute = AboutAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AboutRoute,
} as any)
const AboutFacultyRoute = AboutFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AboutRoute,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AboutRoute,
} as any)
const AboutStaffRoute = AboutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/students': typeof StudentsRoute
  '/about/advisor': typeof AboutAdvisorRoute
  '/about/faculty': typeof AboutFacultyRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/staff': typeof AboutStaffRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/students': typeof StudentsRoute
  '/about/advisor': typeof AboutAdvisorRoute
  '/about/faculty': typeof AboutFacultyRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/staff': typeof AboutStaffRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/students': typeof StudentsRoute
  '/about/advisor': typeof AboutAdvisorRoute
  '/about/faculty': typeof AboutFacultyRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/staff': typeof AboutStaffRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/students'
    | '/about/advisor'
    | '/about/faculty'
    | '/about/founder'
    | '/about/staff'
    | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/students'
    | '/about/advisor'
    | '/about/faculty'
    | '/about/founder'
    | '/about/staff'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/students'
    | '/about/advisor'
    | '/about/faculty'
    | '/about/founder'
    | '/about/staff'
    | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/advisor': {
      id: '/about/advisor'
      path: '/advisor'
      fullPath: '/about/advisor'
      preLoaderRoute: typeof AboutAdvisorRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/faculty': {
      id: '/about/faculty'
      path: '/faculty'
      fullPath: '/about/faculty'
      preLoaderRoute: typeof AboutFacultyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/founder': {
      id: '/about/founder'
      path: '/founder'
      fullPath: '/about/founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/staff': {
      id: '/about/staff'
      path: '/staff'
      fullPath: '/about/staff'
      preLoaderRoute: typeof AboutStaffRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAdvisorRoute: typeof AboutAdvisorRoute
  AboutFacultyRoute: typeof AboutFacultyRoute
  AboutFounderRoute: typeof AboutFounderRoute
  AboutStaffRoute: typeof AboutStaffRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAdvisorRoute: AboutAdvisorRoute,
  AboutFacultyRoute: AboutFacultyRoute,
  AboutFounderRoute: AboutFounderRoute,
  AboutStaffRoute: AboutStaffRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
